graph TD
    sofia_deluca_routine_beach --> sofia_deluca_routine_beach_conversation_decision
    sofia_deluca_routine_beach_conversation_decision --> sofia_deluca_routine_beach_conversation_decision_work
    sofia_deluca_routine_beach_conversation_decision --> sofia_deluca_routine_beach_conversation_decision_how_are_you
    sofia_deluca_routine_beach --> sofia_deluca_routine_beach_flirting